### ISSUE TITLE
Error lanching with xcode

### ISSUE THREAD

**Issue by smad** [adampash/react-native-hot-redux-starter#7]
![image](https://cloud.githubusercontent.com/assets/582359/10817445/1ad5dda6-7e3a-11e5-8bca-9b706126f37b.png)

I'am using 'npm run hot'

**Comment by adampash** [comment]
Make sure you've enabled the Chrome debugger, per the readme:

> On first run, you'll likely receive an error because, in order for hot-loading to work, you need to be debugging in Chrome. Dismiss the error (press escape), then press Cmd+D and click on the Debug in Chrome button. When the Chrome debugger is open and connected, press Cmd+R in the iOS simulator to reload the app. You should now be hot-loading, and all changes you save in your source should update in the app.
